### ISSUE TITLE
Keep the legion alive!

### ISSUE THREAD

**Issue by ChrisE217** [Anti-region-Legion/Anti-region-Legion.github.io#4]
I feel the activity of the anti region legion has plummeted. WE MUST KEEP FIGHTING!! 

#endregions

**Comment by fordprefect480** [comment]
Would love to show my support with a tshirt, but I'm not sure they're still a thing? 
![image](https://user-images.githubusercontent.com/1783639/101423231-8531e400-3948-11eb-98a0-a8fd59da09d7.png)
